#!/usr/bin/env python3
"""check-bytes -- fail the build if a tracked TEXT file carries a raw control
byte.

Why this exists: typing a control-character escape into a tool call (most
often code point zero) sometimes lands the REAL byte in a shipped script, a
plan file or a commit message instead of the handful of characters that were
meant -- the tool takes the escape literally rather than as text describing
one. A raw control byte makes a text file read as binary to grep and diff,
and nothing else in this project's gates reads every tracked file's bytes
looking for one.

What counts as an offending byte: 0x00-0x1F and 0x7F (DEL), MINUS tab (0x09),
newline (0x0A) and carriage return (0x0D) -- the three control bytes every
text file legitimately carries. Form feed (0x0C) and escape (0x1B) are
offenders like any other; they are named here only because it is easy to
assume a formatting byte is exempt the way tab is. Bytes 0x80 and up are
never flagged: those are continuation bytes of a multi-byte UTF-8 character
(an accented letter, an emoji, a box-drawing glyph), never a control code,
and flagging them would fail on ordinary Unicode text.

Scope: every path `git ls-files` tracks, minus what is already known not to be
hand-edited text:
  - a path git's own .gitattributes marks `binary` (or `-text`), asked via
    `git check-attr` so a rule added there later needs no change here;
  - a small extension allow-list for what this project ships that no
    .gitattributes rule (there is none yet) declares: images, fonts, wasm;
  - `.jsonl` files -- append-only logs, not hand-edited text;
  - a minified bundle (its filename contains ".min.") under a `public/vendor/`
    directory -- generated by its own build recipe and regenerated rather
    than patched, so a stray byte in one is not this gate's business. Only
    the bundle itself is exempted; a plain file such as that directory's own
    README is still scanned normally.

A hit is reported as `path:line:column`, one per line, to stderr, and the
script exits 1. Column counts BYTES on the line, not decoded characters: the
offending byte itself is always single-byte ASCII, so its own position is
exact, but an earlier multi-byte character on the same line inflates the
count relative to what an editor would show for that line. Exits 0 with a
one-line summary when the tree is clean.

Root: the current directory, or CHECK_BYTES_ROOT if set -- the test harness
points this at a throwaway git repository so a real tree is never at risk,
the same convention scripts/plan-names.mjs uses (PLAN_NAMES_ROOT) for the
same reason.

Usage:
    check-bytes.py     scan every tracked file under the root, as described
                        above; prints a summary and exits 0, or lists every
                        hit and exits 1
"""
import os
import subprocess
import sys

ALLOWED = {0x09, 0x0A, 0x0D}  # tab, newline, carriage return

# Extensions no .gitattributes rule (there is none yet) declares binary for
# this project. Compared lowercase, against the path's final "."-suffix.
SKIP_EXTENSIONS = {
    # images
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".tiff", ".tif",
    # fonts
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    # wasm
    ".wasm",
    # append-only logs, not hand-edited text
    ".jsonl",
}

ROOT = os.environ.get("CHECK_BYTES_ROOT") or os.getcwd()


def is_offending(b):
    """A byte in the C0 control range or DEL, excluding the three every text
    file legitimately carries."""
    return (b <= 0x1F and b not in ALLOWED) or b == 0x7F


def tracked_files(root):
    out = subprocess.run(
        ["git", "-C", root, "ls-files", "-z"],
        capture_output=True, check=True,
    )
    return [p.decode("utf-8", "surrogateescape") for p in out.stdout.split(b"\0") if p]


def binary_by_attr(root, paths):
    """Paths git's own .gitattributes already marks binary (or -text), via
    one batched `check-attr` call rather than a subprocess per file. A path
    with no matching rule reports nothing at all (not "unspecified"), which
    is why absence from the result -- not an explicit "unset" -- is the
    common case in a tree with no .gitattributes yet."""
    if not paths:
        return set()
    payload = ("\0".join(paths) + "\0").encode("utf-8", "surrogateescape")
    out = subprocess.run(
        ["git", "-C", root, "check-attr", "--stdin", "-z", "--all"],
        input=payload, capture_output=True, check=True,
    )
    fields = out.stdout.decode("utf-8", "surrogateescape").split("\0")
    if fields and fields[-1] == "":
        fields = fields[:-1]
    hits = set()
    for i in range(0, len(fields), 3):
        path, attr, value = fields[i], fields[i + 1], fields[i + 2]
        if (attr == "binary" and value == "set") or (attr == "text" and value == "unset"):
            hits.add(path)
    return hits


def is_vendored_bundle(path):
    """A generated, minified bundle directly inside a public/vendor/
    directory -- never hand-edited, so a stray byte in one is not this
    gate's business. Everything else in that directory (its README, say)
    is still scanned normally."""
    parts = path.split("/")
    for i in range(1, len(parts) - 1):
        if parts[i] == 'vendor' and parts[i - 1] == 'public':
            return ".min." in parts[-1]
    return False


def should_skip(path, attr_binary):
    if path in attr_binary:
        return True
    if is_vendored_bundle(path):
        return True
    _, ext = os.path.splitext(path)
    return ext.lower() in SKIP_EXTENSIONS


def scan_file(root, path):
    """Yield (line, column, byte) for every offending byte, reading raw
    bytes -- never decoded text, so the check does not depend on what
    encoding a file claims to be in."""
    with open(os.path.join(root, path), "rb") as f:
        data = f.read()
    line = 1
    col = 0
    for b in data:
        if b == 0x0A:
            line += 1
            col = 0
            continue
        col += 1
        if is_offending(b):
            yield line, col, b


def main():
    root = ROOT
    paths = tracked_files(root)
    attr_binary = binary_by_attr(root, paths)

    hits = []
    read_errors = []
    for path in paths:
        if should_skip(path, attr_binary):
            continue
        full = os.path.join(root, path)
        if os.path.islink(full):
            continue  # tracked as a link; its target is a different file's problem
        try:
            for line, col, b in scan_file(root, path):
                hits.append((path, line, col, b))
        except OSError as exc:
            read_errors.append((path, exc))

    for path, exc in read_errors:
        sys.stderr.write(f"check-bytes: could not read {path}: {exc}\n")

    if hits:
        for path, line, col, b in hits:
            sys.stderr.write(f"{path}:{line}:{col}: control byte 0x{b:02x}\n")
        names = sorted({path for path, _, _, _ in hits})
        sys.stderr.write(f"\ncheck-bytes: {len(hits)} control byte(s) in {len(names)} file(s):\n")
        for name in names:
            sys.stderr.write(f"  {name}\n")
        sys.stderr.write(
            "\nA control byte other than tab/newline/CR almost always means an escape\n"
            "sequence was typed and the raw byte landed in the file instead of the\n"
            "characters that were meant. Open the file at the reported line and column\n"
            "and replace the byte with that text.\n"
        )
        return 1

    if read_errors:
        return 1

    print(f"check-bytes: {len(paths)} tracked file(s) scanned, no control bytes found")
    return 0


if __name__ == "__main__":
    sys.exit(main())
